In [1]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import numpy as np

### 리스트 ,행렬 선언

In [6]:
#list_name (변수명 설정)= ["ㅇㄹ","ㅁㄴㅇㄹㅇ"...."ㄴㅇㄹ"]

a = [1,2,3]
b = ["a", "b", "c"]
c = [["a"]]


In [7]:
c.append('new_litem')

In [10]:
print(c)

[['a'], 'new_litem']


In [12]:
#배열
a = np.array([1,2,3])
b = np.array(["a","b","c"])
c = np.array([['a'],['a','n'],['a','b'],['a','b','c']])

In [14]:
print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'n']) list(['a', 'b']) list(['a', 'b', 'c'])]


In [19]:
#배열을 1로 채우기
print(np.ones((1,5)))
print(np.ones((3,2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
#배열을 -0으로 채우기
print(np.zeros((1,5)))

[[0. 0. 0. 0. 0.]]


In [23]:
#주어진 범위 안에서 순차적으로 증가하는리스트 만들자

print(np.arange(10))
print(np.arange(3,7, dtype = np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [24]:
#행렬 선언
mat1 = np.array([[1,2,3],[4,5,6]])

#random으로 matrix 만들기
mat2 = np.random.randint(low = 1 , high=10, size = (3,2))
mat3 = np.random.rand(3,2) #정규분포사아에서 숫자를 뽑음

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[4 1]
 [3 2]
 [2 1]]
[[0.01042731 0.12074174]
 [0.50478949 0.41558031]
 [0.9288636  0.84605775]]


### 리스트 인덱싱,슬라이싱

In [27]:
#인덱싱
a = [1,3,4,6,8,9]
print(a[2], a[4],a[-1])

4 8 9


In [29]:
#slicing
b = [1,5,76,8,9,0,12]
print(b[2:])
print(b[:2])
print(b[:])

[76, 8, 9, 0, 12]
[1, 5]
[1, 5, 76, 8, 9, 0, 12]


### reshape

In [30]:
mat1 = np.random.rand(6,3)
print(mat1)

[[0.0353467  0.4362287  0.14265972]
 [0.25640966 0.15029729 0.09124335]
 [0.16528943 0.71826494 0.2918398 ]
 [0.7253344  0.770945   0.05932596]
 [0.67418006 0.81437633 0.33413092]
 [0.48549875 0.90142427 0.80984725]]


In [32]:
#-1:all
print(mat1.reshape(1,-1).shape)
print(mat1.reshape(1,-1))
print("=========")
print(mat1.reshape(-1,1).shape)
print(mat1.reshape(-1,1))

(1, 18)
[[0.0353467  0.4362287  0.14265972 0.25640966 0.15029729 0.09124335
  0.16528943 0.71826494 0.2918398  0.7253344  0.770945   0.05932596
  0.67418006 0.81437633 0.33413092 0.48549875 0.90142427 0.80984725]]
(18, 1)
[[0.0353467 ]
 [0.4362287 ]
 [0.14265972]
 [0.25640966]
 [0.15029729]
 [0.09124335]
 [0.16528943]
 [0.71826494]
 [0.2918398 ]
 [0.7253344 ]
 [0.770945  ]
 [0.05932596]
 [0.67418006]
 [0.81437633]
 [0.33413092]
 [0.48549875]
 [0.90142427]
 [0.80984725]]


In [33]:
print(mat1.reshape(2, 9).shape)
print(mat1.reshape(9, 2))


(2, 9)
[[0.0353467  0.4362287 ]
 [0.14265972 0.25640966]
 [0.15029729 0.09124335]
 [0.16528943 0.71826494]
 [0.2918398  0.7253344 ]
 [0.770945   0.05932596]
 [0.67418006 0.81437633]
 [0.33413092 0.48549875]
 [0.90142427 0.80984725]]


In [35]:
# mat1.reshape(2,5) # 당연히 에러난다

In [36]:
# tensor 형태로 나타내기
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.0353467  0.4362287  0.14265972]
  [0.25640966 0.15029729 0.09124335]]

 [[0.16528943 0.71826494 0.2918398 ]
  [0.7253344  0.770945   0.05932596]]

 [[0.67418006 0.81437633 0.33413092]
  [0.48549875 0.90142427 0.80984725]]]


###  matrix 또는  tensor 형태에서도 slicing 가능

In [37]:

mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [38]:
mat2[:1,:3]

array([[0, 1, 2]])

In [39]:
mat2[3, 0:2]

array([12, 13])

### 사칙연산 

In [40]:
x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [41]:
# add
x + y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [42]:
x - y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [43]:
x * y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [44]:
x / y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [46]:
# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x * z1

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])